### ISSUE TITLE
Unclear closing steps

### ISSUE THREAD

**Issue by Kotenkov** [wemake-services/meta#19]
Can you provide please the proper examples of "Completing a Feature" from [https://github.com/wemake-services/meta/wiki/Closing-issues](url). It would be nice to show the steps itself on example of some issue ,to avoid misunderstanding (e.g the way to create a proper  new branch name) .

**Comment by sobolevn** [comment]
Thanks for the proposal. But, nope. 

I am strongly against any examples in the documentation. 
Since every example must be complete and contain all the required context.

This examples may cause multiple issues in the future. Such as: misunderstanding, a lot of refactoring if the process will change, blind copying without understanding the underlying process.
